### ISSUE TITLE
Comparable Upgrade | Incompatibility

### ISSUE THREAD

**Issue by Melowelsa** [Rusketh/ComparableHoppers2#6]
1) Q: What is your name on spigot?
   A: __Melowelei__

2) Q: What is your Spigot build?
   A: Spigot-v1_12 (git-Spigot-596221b-86aa17f | 1.12-R0.1-SNAPSHOP).

3) Q: What is your CH2 version?
   A: CH2 2.3.3 for MC 1.12.x

4) Q: Do you get any errors in console?
   A: There is no error.

5) Q: Have you read the full OP for the resource (https://www.spigotmc.org/resources/comparable-hoppers-2.45058/
   A: Yes, I read the full OP.
   
6) Q: Please describe the issue you are having.
   A: I can't combine the "Comparable Hopper Upgrade" with all upgrade except "Withlist Hopper Upgrade" and "Blacklist Hopper Upgrade".

7) Q: Please describe how to replicate the issue, being as specific as possible.
   A: Take a normal hopper, put it on the ground. Then, give you a "Comparable Hopper Upgrade" and upgrade the hopper with this.
Then take a "Vacuum Hopper Upgrade" and upgrade the same hopper, then drop item on the hopper, and the hopper will freeze and not do anything more.

8) Q: Anything else you think we should know about your issue?
   A: The option "comparable-upgrade-required" are set to true for all update, and it's the same issue if it's on false.

**Comment by Rusketh** [comment]
I am sorry but I do not understand the issue.

The comparable upgrade is required before a black listing or filter upgrade can be installed this can not be changed and no config option exists for it.

All other upgrades do not require a comparable hopper, but this can be changed by setting "comparable-upgrade-required" to true for that upgrade in the config. This will mean that that upgrade will require a comparable upgrade before it can be installed.

I have tested the config option in 2.3.3 for each item that supports it, with both true and false values. In every instance (1.8.8 and 1.12.2) no errors or issues where found.

**Comment by Rusketh** [comment]
I believe i have found the issue and this relates to #2 witch should be fixed as of 2.3.4.

**Comment by Rusketh** [comment]
Should be fixed as of 2.3.4.

**Comment by Melowelsa** [comment]
Still not be fixed, can you double check it please ? Thanks.
